{% set name = "rainbow-logging-handler" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rainbow_logging_handler-{{ version }}.zip
  sha256: a504c20f1e074cc7f5a5b986c08eb6fb495c9153cffb36b5fa0a587de3a8db63

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - colorama
    - logutils
    - python >=3.6

test:
  imports:
    - rainbow_logging_handler
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rainbow_logging_handler
  summary: Ultimate Python colorized logger with user-custom color
  license: Unlicense
  license_file: LICENSE.txt
  dev_url: https://github.com/laysakura/rainbow_logging_handler

extra:
  recipe-maintainers:
    - goanpeca
